[package]
name = "nftblockd"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive", "env"] }
ureq = "3.0.11"
env_logger = "0.11.8"
log = "0.4.22"
ipnetwork = { version = "0.21.1", features = ["default"] }
thiserror = "2.0.12"
nftables = "0.6.2"
serde_json = "1.0.140"
dotenvy = "0.15.7"